maintenance:
  cost: 20
  unpaid-limit: 2
  per-chunk-cost: 5
scoreboard:
  title: "§aContinent Server"
  minimap-size: 7
  show-coordinates: false
  refresh-interval: 0.5
server-address: "example.com"
colors:
  claimed: "&a"
  unclaimed: "&f"
symbols:
  center: "▣"
  chunk: "▩"
lobby-world: "lobby"
land-world: "world"
war:
  declare-cost: 0
