name: continent
version: '1.0-SNAPSHOT'
main: me.continent.ContinentPlugin
api-version: '1.21'
commands:
  market:
    description: Player market
    usage: /market
  nation:
    description: Nation system command
    aliases: [n]
    usage: /nation <subcommand>
  crown:
    description: Crown system command
    usage: /crown <subcommand>
  war:
    description: War system command
    aliases: [ww]
    usage: /war <subcommand>
  guide:
    description: Provides guide books about kingdom, nation and war
    usage: /guide <topic>
  specialty:
    description: Specialty goods command
    aliases: [spc]
    usage: /specialty <subcommand>
  admin:
    description: Manage wars, economy and maintenance
    usage: /admin <subcommand>
  union:
    description: Manage unions of nations
    aliases: [u]
    usage: /union <subcommand>
  menu:
    description: Open server menu
    aliases: [m]
    usage: /menu
  enterprise:
    description: Manage player enterprises
    usage: /enterprise <subcommand>
  job:
    description: Manage player jobs
    usage: /job <subcommand>
  stat:
    description: Player stat management
    usage: /stat <add>
